#pragma once

#define DNS_SUCCESS 0
#define DNS_ERROR_INVALID_PARAM 1
#define DNS_ERROR_NETWORK_FAILED 2
#define DNS_ERROR_ADAPTER_NOT_FOUND 3
#define DNS_ERROR_ACCESS_DENIED 4
#define DNS_ERROR_TIMEOUT 5
#define DNS_ERROR_INTERNAL 6
